### ISSUE TITLE
2.5.6 and 2.6 are exactly the same

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [wilkinsonlab/SADI-Specification#2]
The paragraph is identical:

2.5.6 Minimal Constraints on Data Modeling

Aside from the constraint of the previous section, SADI does not provide any rules about how service input and output data should be modeled in RDF. Service providers are free to encode the data using any OWL or RDFS ontologies deemed suitable. Further, the input and output RDF documents for a service invocation consist only of data that is consumed or generated by the service, respectively. There are no SADI-specific messaging structures required within the input/ output RDF documents.

2.6 Relationship to Other Web Service Standards

Aside from the constraint of the previous section, SADI does not provide any rules about how service input and output data should be modeled in RDF. Service providers are free to encode the data using any OWL or RDFS ontologies deemed suitable. Further, the input and output RDF documents for a service invocation consist only of data that is consumed or generated by the service, respectively. There are no SADI-specific messaging structures required within the input/ output RDF documents.

**Comment by markwilkinson** [comment]
fixed

On 01/26/2016 12:52 PM, Mikel Egaña Aranguren wrote:

> The paragraph is identical:
> 
> 2.5.6 Minimal Constraints on Data Modeling
> 
> Aside from the constraint of the previous section, SADI does not 
> provide any rules about how service input and output data should be 
> modeled in RDF. Service providers are free to encode the data using 
> any OWL or RDFS ontologies deemed suitable. Further, the input and 
> output RDF documents for a service invocation consist only of data 
> that is consumed or generated by the service, respectively. There are 
> no SADI-specific messaging structures required within the input/ 
> output RDF documents.
> 
> 2.6 Relationship to Other Web Service Standards
> 
> Aside from the constraint of the previous section, SADI does not 
> provide any rules about how service input and output data should be 
> modeled in RDF. Service providers are free to encode the data using 
> any OWL or RDFS ontologies deemed suitable. Further, the input and 
> output RDF documents for a service invocation consist only of data 
> that is consumed or generated by the service, respectively. There are 
> no SADI-specific messaging structures required within the input/ 
> output RDF documents.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/wilkinsonlab/SADI-Specification/issues/2.

## 

## 

Mark Wilkinson
Madrid, Spain
