### ISSUE TITLE
Extra space in example 2

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [wilkinsonlab/SADI-Specification#3]
Example 2

@prefix hello: http://sadiframework.org/examples/hello.owl# .
@prefix input: http://sadiframework.org/data/examples/hello-input_!!!!EXTRA-SPACE!!!_.n3# .

**Comment by markwilkinson** [comment]
fixed

On 01/26/2016 12:54 PM, Mikel Egaña Aranguren wrote:

> Example 2
> 
> @prefix https://github.com/prefix hello: 
> http://sadiframework.org/examples/hello.owl# .
> @prefix https://github.com/prefix input: 
> http://sadiframework.org/data/examples/hello-input_!!!!EXTRA-SPACE!!!_.n3# 
> http://sadiframework.org/data/examples/hello-input_%21%21%21%21EXTRA-SPACE%21%21%21_.n3# 
> .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/wilkinsonlab/SADI-Specification/issues/3.

## 

## 

Mark Wilkinson
Madrid, Spain
