### ISSUE TITLE
Service type ontologies?

### ISSUE THREAD

**Issue by mikel-egana-aranguren** [wilkinsonlab/SADI-Specification#4]
In the Service Metadata section: 

"service type URI(s) -- one or more rdf:type URIs indicating the type of service. These URIs may be used to categorize the service by a wide variety of criteria, such as the task performed, the algorithm utilized, or the intended users of the service."

Are there any commonly used ontologies whose clases one can use in the rdf:type triples? It would be helpful to have some pointers here as examples

**Comment by markwilkinson** [comment]
added reference to the Operation branch of EDAM

On 01/26/2016 12:58 PM, Mikel Egaña Aranguren wrote:

> In the Service Metadata section:
> 
> "service type URI(s) -- one or more rdf:type URIs indicating the type 
> of service. These URIs may be used to categorize the service by a wide 
> variety of criteria, such as the task performed, the algorithm 
> utilized, or the intended users of the service."
> 
> Are there any commonly used ontologies whose clases one can use in the 
> rdf:type triples? It would be helpful to have some pointers here as 
> examples
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/wilkinsonlab/SADI-Specification/issues/4.

## 

## 

Mark Wilkinson
Madrid, Spain
